docs/03-flowable-api.md

`.unshit()`  dose nothing. According to the comment it should be `.shift()`.

Fix the unexpected code

---

packages/rsocket-core/src/RSocketClient.js
packages/rsocket-core/src/__tests__/RSocketClient-test.js

Now, RSocket had the ability to send metadata with the setupFrame in rsocket-java version. And this PR is for supporting this feature in rsocket-js version. 
PS: We could find the new way that flags calculate [here](https://github.com/rsocket/rsocket-java/blob/102590efb48e9de9359aba984ac8a4dd6f054fb3/rsocket-core/src/main/java/io/rsocket/frame/SetupFrameFlyweight.java#L70) (rsocket-java).

Support for sending metadata with setupFrame on js client

---

packages/rsocket-core/src/RSocketClient.js

Unlike other browsers, when Internet Explorer and Edge experience more than 30 seconds of inactivity on a WebSocket connection, the browsers will start sending the server unsolicited "pong" frames. These unexpected frames can cause issues server-side if not anticipated, potentially overwhelming the server or killing the client connection (Network Error 12030 in both browsers).
Here are a few examples of other people encountering this issue:
https://github.com/http-kit/http-kit/issues/322
https://stackoverflow.com/questions/43811618/microsoft-edge-websocket-error-network-error-12030-using-websockets-after-som
https://stackoverflow.com/questions/32066963/edge-browser-websocket-connection-will-be-automatically-closed-after-an-idle-tim
Since the WebSocket API doesn't allow for controlling …

Add warning check for browser bug

---

docs/01-client-configuration.md

Fixes typo in docs.  The parameter was shown as `uri` when it should be `url`.

Fix RSocketWebSocketClient constructor param in docs

---

packages/rsocket-core/src/RSocketClient.js
packages/rsocket-core/src/__tests__/RSocketClient-test.js

RSocket supports including a payload in the initial connection frame when setting up a connection.
This is implemented in the rsocket-cpp client, so I'm bringing the js client up to feature parity.

RSocketClient: Allow payload in conn setup frame

---

docs/02-client-api.md

Updates `02-client-api.md` documentation with a description for `requestChannel`, based on discussions  and information/understanding gathered from https://github.com/rsocket/rsocket-js/issues/52.
Please let me know if the description is incorrect or misleading in any way, as that likely indicates a misunderstanding on my part which I would appreciate corrected.

Update description of requestChannel in 02-client-api.md

---

README.md
docs/00-index.md

Updates the link to the main rsocket documentation site in `README.md`.

Update link to rsocket.io website in documentation

---

package.json

Addresses #60 by prefixing npm scripts that set env variables with [cross-env](https://www.npmjs.com/package/cross-env).

[#60] prefix build and jest commands with cross-env for Windows support

---

packages/rsocket-core/src/RSocketClient.js

This PR provides a fix to the access to `window` variable within the node env in strict mode
which led to failure

fixes the failure in case of running the RSocketClient in node env

---

packages/rsocket-core/src/LiteBuffer.js

This PR fixes `Buffer#write` method behavior according to the specified in the node docs -> https://nodejs.org/api/buffer.html#buffer_buf_write_string_offset_length_encoding.
For more info see #72

fixes Buffer polyfill `Buffer#write` method behaviour

---

packages/rsocket-flowable/src/Single.js

A `Single` produced by `Single.error()` should be assignable to any `Single<T>` type.
```ts
const willAlwaysError = Single.error(new Error());
const mySingle: Single<Foo> = willAlwaysError; // <-- this should always typecheck
```
This PR changes the default value of `Single.error`'s type param to be `never`, making it assignable to any `Single<T>` type.
This is the direct analogy of the default of `never` (same as `empty`) in TypeScript's [`Promise.reject`](https://github.com/microsoft/TypeScript/blob/c6cdc63b9c8d557dfa8ff0069972dc238292bb4e/lib/lib.es2015.promise.d.ts#L136):
```ts
reject<T = never>(reason?: any): Promise<T>;
```

makes Single.error() return a Single<empty>

---

packages/rsocket-flowable/src/Flowable.js

Same as #76, but this time for `Flowable`.
DefinitelyTyped PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43318

makes Flowable.error() and Flowable.never() return a Flowable<empty>

---

packages/rsocket-examples/src/CompositeMetadataExample.js

According to comment: https://github.com/rsocket/rsocket-js/issues/72#issuecomment-584827432
Tested on our own code base.

Fix composite metadata example

---

packages/rsocket-flowable/src/Single.js

This PR adds `Single.never()`, analogous to `Flowable.never()`:
https://github.com/rsocket/rsocket-js/blob/bb11e451d50ef5520580611661627aa14ee1a3f0/packages/rsocket-flowable/src/Flowable.js#L75-L82

adds Single.never()

---

packages/rsocket-core/src/AuthMetadata.js
packages/rsocket-core/src/CompositeMetadata.js
packages/rsocket-core/src/LiteBuffer.js
packages/rsocket-core/src/RSocketBufferUtils.js
packages/rsocket-core/src/RoutingMetadata.js
packages/rsocket-core/src/WellKnownAuthType.js
packages/rsocket-core/src/__tests__/AuthMetadata-test.js
packages/rsocket-core/src/__tests__/CompositeMetadata-test.js
packages/rsocket-core/src/__tests__/LiteBuffer-test.js
packages/rsocket-core/src/__tests__/RoutingMetadata-test.js
packages/rsocket-core/src/index.js
packages/rsocket-examples/src/CompositeMetadataExample.js

This PR provides support for Routing Metadata and Auth Metadata as well as bring some minor fixes to LiteBuffer + non-breaking refactoring of CompositeMetadata to follow JS usage patterns
closes #88  
Signed-off-by: Oleh Dokuka <shadowgun@i.ua>

Provides Auth Metadata and Routing Metadata Support

---

packages/rsocket-core/src/RSocketMachine.js
packages/rsocket-core/src/__tests__/RSocketClient-test.js

This PR is an attempt to solve https://github.com/rsocket/rsocket-js/issues/115 by explicitly calling `_handleStreamError` after sending an error with `_sendStreamError`. From what I understand, there should not be any unexpected side effects as every receiver is only terminated once. 
The PR also includes a test, where the flow might not be immediately obvious but it effectively replicates the situation described in https://github.com/rsocket/rsocket-java/issues/978. I'm not sure if there is a more concise way to express this scenario.

terminates the stream upon sending an error

---

packages/rsocket-core/src/LiteBuffer.js

From the private chatting with our users, it turned out that `LiteBuffer` which extends `UInt9Array` may have some issues if it relies on the parent constructor behavior in the case of Safari 12 or 13.
Signed-off-by: Oleh Dokuka <odokuka@vmware.com>
Signed-off-by: Oleh Dokuka <shadowgun@i.ua>

ensures length and offset are calculated properly

---

packages/rsocket-core/src/RSocketServer.js
packages/rsocket-core/src/__tests__/RSocketServer-test.js

This PR ensures that the `RSocketServer._connections` `Set` is cleaned when a connection goes away.
Related issue: https://github.com/scalecube/scalecube-js/issues/269 
Signed-off-by: Oleh Dokuka <odokuka@vmware.com>
Signed-off-by: Oleh Dokuka <shadowgun@i.ua>

fixes RSocketMachine leak on the server-side

---

packages/rsocket-core/package.json
packages/rsocket-core/src/Invariant.js
packages/rsocket-core/src/RSocketBinaryFraming.js
packages/rsocket-core/src/RSocketClient.js
packages/rsocket-core/src/RSocketEncoding.js
packages/rsocket-core/src/RSocketFrame.js
packages/rsocket-core/src/RSocketLease.js
packages/rsocket-core/src/RSocketMachine.js
packages/rsocket-core/src/RSocketResumableTransport.js
packages/rsocket-core/src/RSocketSerialization.js
packages/rsocket-core/src/RSocketServer.js
packages/rsocket-core/src/__mocks__/MockDuplexConnection.js

This PR proposes removing the [fbjs](https://github.com/facebook/fbjs) dependency and removes it from rsocket-core. 
At the moment, [`fbjs`](https://github.com/facebook/fbjs) is the only major 3rd party dependency. However, very few functions from `fbjs` are actually used - mostly `invariant`. The downside of depending on `fbjs`  is the following transitive closure: 
https://github.com/facebook/fbjs/blob/5300adaec134f532391dfac65d574cc066fe593e/packages/fbjs/package.json#L65-L73. Removing `fbjs` could make rscoket-js effectively a zero dependency package which could facilitate the adoption. 
Additionally, the [README](https://github.com/facebook/fbjs/blob/master/README.md) page of `fbjs` states that "If you are consuming the code here and you are not also a Facebook project, be prepared …

removes dependency on fbjs from rsocket-core

---

packages/rsocket-examples/package.json
packages/rsocket-examples/src/SimpleCli.js
packages/rsocket-flowable/package.json
packages/rsocket-flowable/src/Flowable.js
packages/rsocket-flowable/src/FlowableMapOperator.js
packages/rsocket-flowable/src/FlowableProcessor.js
packages/rsocket-flowable/src/FlowableTakeOperator.js
packages/rsocket-flowable/src/Invariant.js
packages/rsocket-flowable/src/Single.js
packages/rsocket-flowable/src/__mocks__/MockFlowableSubscriber.js
packages/rsocket-flowable/src/__tests__/Flowable-test.js
packages/rsocket-flowable/src/__tests__/Single-test.js
packages/rsocket-types/package.json
packages/rsocket-websocket-client/package.json
packages/rsocket-websocket-client/src/RSocketWebSocketClient.js

This PR is a continuation of https://github.com/rsocket/rsocket-js/pull/133. In this PR, `fbjs` is removed from: 
* `rsocket-examples`
* `rsocket-flowable`
* `rsocket-types`
* `rsocket-websocket-client`

replace fbjs in flowable/types/ws

---

examples/RSocketExampleConditionalRequestClient.js
packages/rsocket-tck/package.json
packages/rsocket-tck/src/Deferred.js
packages/rsocket-tck/src/RSocketTckClient.js
packages/rsocket-tck/src/RSocketTckRequestResponseSubscriber.js
packages/rsocket-tck/src/RSocketTckRequestStreamSubscriber.js
packages/rsocket-tcp-client/package.json
packages/rsocket-tcp-client/src/RSocketTcpClient.js
packages/rsocket-tcp-server/package.json
packages/rsocket-websocket-server/package.json
packages/rsocket-websocket-server/src/RSocketWebSocketServer.js
yarn.lock

This PR is a continuation of #134. In this PR, fbjs is removed from:
* rsocket-tck
* rsocket-tcp-client
* rsocket-tcp-server
* rsocket-websocket-server
None of the artifacts depends on `fbjs` now. The only remaining usage of the dependency is the jest test configuration. 
`rsocket-tck` was covered by tests, so I ran it manually with `yarn tck`. However, the only place where I found the compatible TCK was https://github.com/rsocket/rsocket-tck/pull/35 - I couldn't find a way to run the JS tck against any other server. 
```
rsocket-js % yarn tck
yarn run v1.22.4
$ yarn run build && node ./packages/rsocket-tck/build/index.js "$@"
$ cross-env NODE_ENV=production node ./scripts/build.js
Building packages
=> rsocket-core (npm)
=> rsocket-examples (npm)
=> rsocket-flowable (npm)
=> rsocket-tck …
```

remove fbjs from tck/websocket-server

---

packages/rsocket-core/src/ClientServerMultiplexerDemultiplexer.ts
packages/rsocket-core/src/RSocket.ts
packages/rsocket-core/src/RSocketConnector.ts
packages/rsocket-core/src/RSocketServer.ts
packages/rsocket-core/src/RSocketSupport.ts
packages/rsocket-core/src/RequestChannelStream.ts
packages/rsocket-core/src/RequestFnFStream.ts
packages/rsocket-core/src/RequestResponseStream.ts
packages/rsocket-core/src/RequestStreamStream.ts
packages/rsocket-core/src/Transport.ts
packages/rsocket-core/src/index.ts
packages/rsocket-examples/src/ClientServerRequestResponseExampleTcp.ts
packages/rsocket-tcp-client/src/TcpDuplexConnection.ts
packages/rsocket-tcp-client/src/__tests__/TcpDuplexConnection.spec.ts
packages/rsocket-tcp-client/src/__tests__/__snapshots__/TcpDuplexConnection.spec.ts.snap
packages/rsocket-tcp-server/src/TcpDuplexConnection.ts
packages/rsocket-tcp-server/src/TcpServerTransport.ts
packages/rsocket-websocket-client/src/WebsocketClientTransport.ts
packages/rsocket-websocket-client/src/WebsocketDuplexConnection.ts
packages/rsocket-websocket-client/src/__tests__/WebsocketDuplexConnection.spec.ts
packages/rsocket-websocket-client/src/__tests__/__snapshots__/WebsocketDuplexConnection.spec.ts.snap
packages/rsocket-websocket-server/src/WebsocketDuplexConnection.ts
packages/rsocket-websocket-server/src/WebsocketServerTransport.ts

This PR reworks responsibilities of the DuplexConnection to ensure that in the future it exposes required functionality. The main goal of these changes is to make sure we can access upcoming QUIC/WebTransport multiplexing/demultiplexing capabilities exposed on the low-level connection API (see the following [example](https://www.w3.org/TR/webtransport/#example-sending-stream)).
Signed-off-by: Oleh Dokuka <odokuka@vmware.com>
Signed-off-by: Oleh Dokuka <oleh.dokuka@icloud.com>

moves multiplexing/demultiplexing to the DuplexConnection level

---

packages/rsocket-core/src/RSocketConnector.ts
packages/rsocket-core/src/RSocketServer.ts

Fixes an NPE when attempting to leverage `remotePeer` to invoke requests to the original requester.
```js
{
accept: async (payload, remotePeer) => {
remotePeer.requestResponse(
{
data: Buffer.from("hello"),
metadata: undefined,
},
{
onNext(payload: Payload, isComplete: boolean) {},
onComplete(): void {},
onError(error: Error): void {
// now properly rejected with REJECTED RSocketError
// rather than unhandled NPE
console.error(error);
},
onExtension(
extendedType: number,
content: Buffer | null | undefined,
canBeIgnored: boolean
): void {},
}
);
...
}
}
```

fix: fixes npe when rejecting responder request

---

packages/rsocket-core/src/RSocketConnector.ts
packages/rsocket-core/src/RSocketServer.ts

duplicate of https://github.com/rsocket/rsocket-js/pull/176 but with base as `dev` rather than `dev-lease`.

fix: streamsHandler bindings

---

packages/rsocket-core/__tests__/RSocketServer.spec.ts

Adds a unit test to validate rejecting of an unsupported first frame in `RSocketServer`.

test: add test for rejecting unsupported first frame

---

packages/rsocket-websocket-client/package.json
packages/rsocket-websocket-client/src/WebsocketClientTransport.ts
packages/rsocket-websocket-client/src/WebsocketDuplexConnection.ts
packages/rsocket-websocket-client/src/__tests__/WebsocketDuplexConnection.spec.ts

Fixes #183.
Defaults to global `WebSocket` reference in `rsocket-websocket-client` for browser compatibility. non-browser environments can satisfy the dependency via the `wsCreator` configuration property.

fix: default WebSocket reference in rsocket-websocket-client to global browser reference

---

packages/rsocket-composite-metadata/src/CompositeMetadata.ts
packages/rsocket-composite-metadata/src/RoutingMetadata.ts
packages/rsocket-examples/package.json
packages/rsocket-examples/src/ClientServerCompositeMetadataRouteExample.ts
packages/rsocket-examples/src/shared/logger.ts

Adds an example of composite metadata with routing, in order to exercise and proof composite metadata additions.

feat: composite metadata routing example

---

packages/rsocket-core/src/RSocketMachine.js

Addresses #198 
Add Metadata flag as needed when sending stream payload.
Metadata should be included in encoded payloads.

fix: add Metadata flag when sending stream payload which has metadata

---

README.md

Updates README to point visitors to the master branch for source related to the `0.x.x` releases on NPM.

docs: updates readme to callout master branch as source for 0.x.x versions

---

.github/workflows/build.yml

Splits compile and test workflow jobs to run separately so that we can more easily see which stage of the build may be experiencing issues.
Previously `test` required `compile` to be run first, but with recent changes, tests now do compilation just in time.

chore: split ci workflow compile and test jobs to run seperate

---

lerna.json
packages/rsocket-adapter-rxjs/package.json
packages/rsocket-adapter-rxjs/src/Requesters.ts
packages/rsocket-composite-metadata/package.json
packages/rsocket-core/package.json
packages/rsocket-examples/package.json
packages/rsocket-messaging/package.json
packages/rsocket-tcp-client/package.json
packages/rsocket-tcp-server/package.json
packages/rsocket-websocket-client/package.json
packages/rsocket-websocket-server/package.json

Addressed feedback: https://github.com/rsocket/rsocket-js/issues/158#issuecomment-1208040376
Allow optional `metadata` argument in rxjs requesters
Allows for:
```ts
const rsocket = await connector.connect();
let requestResponse = RxRequestersFactory.requestResponse(
"Hello World",
stringCodec,
stringCodec
);
let stringObservable = requestResponse(rsocket);
```
Where previously passing `new Map()` would have been required.
```ts
let stringObservable = requestResponse(rsocket, new Map());
```

Optional metadata for rxjs requesters

---

packages/rsocket-adapter-rxjs/src/Requesters.ts

closes #234 
unexpectedly, the index is a local variable per subscription, thus the second subscription starts indexing from 0 once again even though the element is a second one (index should be 1 in that case). Therefore, to overcome this problem the PR introduces a local variable to track the first element.
Signed-off-by: Oleh Dokuka <odokuka@vmware.com>
Signed-off-by: Oleh Dokuka <oleh.dokuka@icloud.com>

fixes request channel to drop second element

---

packages/rsocket-core/src/Codecs.ts

Fix typo with `FRAME_TYPE_OFFSET`.
Replicates and closes #216 to overcome missing DCO check in original PR.

fix: FRAME_TYPE_OFFSET typo

---

packages/rsocket-core/package.json
packages/rsocket-flowable/package.json
packages/rsocket-tck/package.json
packages/rsocket-tcp-client/package.json
packages/rsocket-tcp-server/package.json
packages/rsocket-types/package.json
packages/rsocket-websocket-client/package.json
packages/rsocket-websocket-server/package.json
scripts/build.js

Running the the build script on windows produces incorrect output.
- Build script normalizes file paths to posix to support Windows and Linux.
Source files are now transpiled when build script is run on Windows.
This should allow me to re-publish a new version from `master` to address #275

fix: build script supports Windows
